name: Generate plugins
on:
    release:
        types: [published]
    push:
        branches:
            - master
            - versions/*
    pull_request: null

env:
    CHECKOUT_SUBMODULES: ""
    GENERATE_PLUGINS_FILTER: ""
    GENERATE_PLUGINS_SLUGS: ""
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: dev-master

jobs:
    provide_data:
        name: Provide configuration to generate plugins
        runs-on: ubuntu-24.04
        steps:
            -   uses: actions/checkout@v5
                with:
                    submodules: ${{ env.CHECKOUT_SUBMODULES }}

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: ramsey/composer-install@v3

            -   id: output_data
                run: |
                    quote=\'
                    filter_arg="--filter=$(echo '${{ env.GENERATE_PLUGINS_FILTER }}' | sed -e 's/ / --filter=/g')"
                    slugs_arg="--slugs=$(echo '${{ env.GENERATE_PLUGINS_SLUGS }}' | sed -e 's/ / --slugs=/g')"
                    echo "plugin_config_entries=$(vendor/bin/monorepo-builder plugin-config-entries-json $(echo $filter_arg) $(echo $slugs_arg) --config=config/monorepo-builder/plugin-config-entries-json.php)" >> $GITHUB_OUTPUT
                    echo "retention_days_for_generated_plugins=$(vendor/bin/monorepo-builder env-var RETENTION_DAYS_FOR_GENERATED_PLUGINS --config=config/monorepo-builder/env-var.php)" >> $GITHUB_OUTPUT
                    echo "local_package_owners=$(vendor/bin/monorepo-builder local-package-owners --config=config/monorepo-builder/local-package-owners.php)" >> $GITHUB_OUTPUT
                    echo "git_base_branch=$(vendor/bin/monorepo-builder env-var GIT_BASE_BRANCH --config=config/monorepo-builder/env-var.php)" >> $GITHUB_OUTPUT
                    echo "git_user_name=$(vendor/bin/monorepo-builder env-var GIT_USER_NAME --config=config/monorepo-builder/env-var.php)" >> $GITHUB_OUTPUT
                    echo "git_user_email=$(vendor/bin/monorepo-builder env-var GIT_USER_EMAIL --config=config/monorepo-builder/env-var.php)" >> $GITHUB_OUTPUT
        outputs:
            plugin_config_entries: ${{ steps.output_data.outputs.plugin_config_entries }}
            retention_days: ${{ steps.output_data.outputs.retention_days_for_generated_plugins }}
            local_package_owners: ${{ steps.output_data.outputs.local_package_owners }}
            git_base_branch: ${{ steps.output_data.outputs.git_base_branch }}
            git_user_name: ${{ steps.output_data.outputs.git_user_name }}
            git_user_email: ${{ steps.output_data.outputs.git_user_email }}

    # Build plugin => downgrade => (maybe) scope => (maybe) upload to release and deploy to dist repo
    process:
        name: Generate plugin "${{ matrix.pluginConfig.plugin_slug }}"
        needs: provide_data
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                pluginConfig: ${{ fromJson(needs.provide_data.outputs.plugin_config_entries) }}
        steps:
            -   name: Checkout code
                uses: actions/checkout@v5
                with:
                    submodules: ${{ env.CHECKOUT_SUBMODULES }}

            -   name: Create build folder
                run: mkdir build && mkdir build/dist-plugin

            -   name: Install zip
                uses: montudor/action-zip@v1.0.0

            # pcre.jit=0 => @see https://github.com/composer/composer/issues/9595
            -   name: Use PHP 8.1
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none
                    ini-values: pcre.jit=0
             

            -   name: Install root dependencies
                uses: ramsey/composer-install@v3

    ###########################################################################
    # Downgrade plugin
    ###########################################################################

            # "custom-bump-interdependency" temporarily needed because of bug:
            # https://github.com/symplify/symplify/issues/2773
            -   name: Localize package paths
                run: |
                    vendor/bin/monorepo-builder custom-bump-interdependency --config=config/monorepo-builder/custom-bump-interdependency.php "dev-${{ needs.provide_data.outputs.git_base_branch }}"
                    vendor/bin/monorepo-builder localize-composer-paths --config=config/monorepo-builder/localize-composer-paths.php ${{ matrix.pluginConfig.path }}/composer.json --ansi
            ###########################################################################
            # When building bundles (i.e. containing 2 or more extension plugins), if 2 extensions
            # contain the same entry under "replace" in composer.json, then "require"ing both of
            # them in the bundle fails.
            #
            # For instance, several plugins replace "pop-schema/schema-commons", producing
            # the following error message:
            #
            #   > Only one of these can be installed: pop-schema/schema-commons[dev-master], gatographql-pro/php-constants-and-environment-variables-via-schema[dev-master], gatographql-pro/helper-function-collection[dev-master]. [gatographql-pro/php-constants-and-environment-variables-via-schema, gatographql-pro/helper-function-collection] replace pop-schema/schema-commons and thus cannot coexist with it.
            #
            # As a solution, when generating the bundle plugin, remove all the "replace" entries
            # in the composer.json for the included plugins, and move them to the bundle composer.json
            ###########################################################################
            -   name: "Bundles: Transfer the 'replace' entries in composer.json, from the contained plugins to the bundle"
                run: |
                    vendor/bin/monorepo-builder transfer-composer-replace-entries-from-plugins-to-bundle --config=config/monorepo-builder/transfer-composer-replace-entries-from-plugins-to-bundle.php "${{ matrix.pluginConfig.path }}/composer.json" --exclude-replace="${{ matrix.pluginConfig.exclude_replace }}"
                if: ${{ matrix.pluginConfig.is_bundle }}

            ###########################################################################
            # When building standalone plugins, the "replace" entries from the bundled
            # extensions must be ignored, as these must also be contained within the
            # standalone plugin (which also contains Gato GraphQL).
            #
            # Because standalone plugins are bundles, in the previous step the
            # "replace" entries have been moved up from the bundled extensions
            # to the bundle's composer.json. Now, remove them.
            ###########################################################################
            -   name: "Standalone plugins: Remove the 'replace' entries in composer.json (originally from the contained plugins, now in the bundle)"
                run: |
                    vendor/bin/monorepo-builder remove-composer-replace-entries --config=config/monorepo-builder/remove-composer-replace-entries.php "${{ matrix.pluginConfig.path }}/composer.json"
                if: ${{ matrix.pluginConfig.is_standalone_plugin }}

            -   name: Install plugin dependencies, avoiding v2 platform check
                run: |
                    composer config platform-check false --no-interaction --ansi
                    composer install --no-progress --no-interaction --ansi
                working-directory: ${{ matrix.pluginConfig.path }}

            # before_downgrade_code.sh => Hacks to fix the codebase in preparation of the Rector downgrade
            -   name: Custom bash script to fix items in the code in preparation for the Rector downgrade
                run: "$GITHUB_WORKSPACE/${{ matrix.pluginConfig.bashScripts.before_downgrade_code }}"
                working-directory: ${{ matrix.pluginConfig.path }}
                if: ${{ matrix.pluginConfig.bashScripts.before_downgrade_code }}

            # additional_rector_after_configs => Hack to fix bug: https://github.com/rectorphp/rector/issues/5962
            -   name: Downgrade code for production (to PHP 7.4)
                run: ci/downgrade/downgrade_code.sh "${{ matrix.pluginConfig.rector_downgrade_config }}" "" "${{ matrix.pluginConfig.path }}" "${{ matrix.pluginConfig.additional_rector_before_configs }}" "${{ matrix.pluginConfig.additional_rector_after_configs }}" "${{ needs.provide_data.outputs.local_package_owners }}"
